---
apiVersion: v1
kind: Service
metadata:
    name: weatherapp-service
spec:
    selector:
        app: weatherapp-deploy
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 5000
    type: LoadBalancer